BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "AspectRatio" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Award" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"PresenterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PresenterID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book" (
	"ID"	TEXT NOT NULL,
	"OriginalTitle"	TEXT,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"TypeID"	TEXT,
	"CastStatusID"	TEXT,
	"CrewStatusID"	TEXT,
	"ConnectionID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CastStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CrewStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ConnectionID") REFERENCES "Connection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Award" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"AwardID"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	"Winner"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AwardID") REFERENCES "Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Cast" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"CharacterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CharacterID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Crew" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"PersonID"	TEXT,
	"DepartmentID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Genre" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"GenreID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("GenreID") REFERENCES "Genre"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Image" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"ImageID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "ImageType" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Language" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"LanguageID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Score" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"Score"	TEXT,
	"Date"	TEXT,
	"CompanyID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Text" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_User" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"UserID"	TEXT,
	"PublicationID"	TEXT,
	"UserStatusID"	TEXT,
	"PriorityID"	TEXT,
	"EnglishExplanation"	TEXT,
	"GermanExplanation"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PriorityID") REFERENCES "Priority"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserID") REFERENCES "User"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Book_Weblink" (
	"ID"	TEXT NOT NULL,
	"BookID"	TEXT,
	"WeblinkID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("WeblinkID") REFERENCES "Weblink"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "BusinessModel" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "CDROMDriveSpeed" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "CPU" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Camera" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Lenses"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Certification" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"ImageID"	TEXT,
	"CountryID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "CinematographicProcess" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Color" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Company" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"NameAddOn"	TEXT,
	"TypeID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Connection" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"ConnectionID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ConnectionID") REFERENCES "Connection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "CopyProtection" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Country" (
	"ID"	TEXT NOT NULL,
	"OriginalShortName"	TEXT,
	"OriginalName"	TEXT,
	"EnglishShortName"	TEXT,
	"EnglishName"	TEXT,
	"GermanShortName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Department" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Difficulty" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "DirectX" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Driver" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Edition" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Employer" (
	"ID"	TEXT NOT NULL,
	"CompanyID"	TEXT,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode" (
	"ID"	TEXT NOT NULL,
	"OriginalTitle"	TEXT,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"SeriesID"	TEXT,
	"SeasonNo"	TEXT,
	"EpisodeNo"	TEXT,
	"CastStatusID"	TEXT,
	"CrewStatusID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CastStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CrewStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Award" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"AwardID"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	"Winner"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AwardID") REFERENCES "Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Award_Person" (
	"ID"	TEXT NOT NULL,
	"Episode_AwardID"	TEXT,
	"PersonID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Episode_AwardID") REFERENCES "Episode_Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Cast" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"ActorID"	TEXT,
	"EnglishDubberID"	TEXT,
	"GermanDubberID"	TEXT,
	"CharacterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ActorID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CharacterID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EnglishDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("GermanDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Certification" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"CertificationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CertificationID") REFERENCES "Certification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_CompanyCredits" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"CompanyID"	TEXT,
	"DepartmentID"	TEXT,
	"CountryID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Crew" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"PersonID"	TEXT,
	"DepartmentID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_FilmLength" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"Length"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_FilmingDate" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_FilmingLocation" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"LocationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("LocationID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Image" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"ImageID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "ImageType" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_ProductionDate" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_ReleaseDate" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"ReleaseDate"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Runtime" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"Runtime"	TEXT,
	"EditionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Episode_Text" (
	"ID"	TEXT NOT NULL,
	"EpisodeID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EpisodeID") REFERENCES "Episode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "FilmFormat" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Gender" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Genre" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Hardware" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Image" (
	"ID"	TEXT NOT NULL,
	"FileName"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Image_Source" (
	"ID"	TEXT NOT NULL,
	"ImageID"	TEXT,
	"CompanyID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "ImageType" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "InputDevice" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "InputDeviceFeature" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Laboratory" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"LocationID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LocationID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Language" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Location" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
    "LocationID"    TEXT,
	"CountryID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY("LocationID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "MacOSSprocket" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "MediaType" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie" (
	"ID"	TEXT NOT NULL,
	"OriginalTitle"	TEXT,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"TypeID"	TEXT,
	"Budget"	TEXT,
	"WorldwideGross"	TEXT,
	"WorldwideGrossDate"	TEXT,
	"CastStatusID"	TEXT,
	"CrewStatusID"	TEXT,
	"ConnectionID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CastStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ConnectionID") REFERENCES "Connection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CrewStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_AspectRatio" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"AspectRatioID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AspectRatioID") REFERENCES "AspectRatio"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Award" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"AwardID"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	"Winner"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AwardID") REFERENCES "Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Award_Person" (
	"ID"	TEXT NOT NULL,
	"Movie_AwardID"	TEXT,
	"PersonID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Movie_AwardID") REFERENCES "Movie_Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Camera" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"CameraID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CameraID") REFERENCES "Camera"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Cast" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"ActorID"	TEXT,
	"EnglishDubberID"	TEXT,
	"GermanDubberID"	TEXT,
	"CharacterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ActorID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CharacterID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EnglishDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("GermanDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Certification" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"CertificationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CertificationID") REFERENCES "Certification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_CinematographicProcess" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"CinematographicProcessID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CinematographicProcessID") REFERENCES "CinematographicProcess"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Color" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"ColorID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ColorID") REFERENCES "Color"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_CompanyCredits" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"CompanyID"	TEXT,
	"DepartmentID"	TEXT,
	"CountryID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Country" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"CountryID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Crew" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"PersonID"	TEXT,
	"DepartmentID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_FilmLength" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"Length"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_FilmingDate" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_FilmingLocation" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"LocationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LocationID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Genre" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"GenreID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("GenreID") REFERENCES "Genre"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Image" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"ImageID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "ImageType" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Laboratory" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"LaboratoryID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LaboratoryID") REFERENCES "Laboratory"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Language" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"LanguageID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_NegativeFormat" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"FilmFormatID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("FilmFormatID") REFERENCES "FilmFormat"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_PrintedFilmFormat" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"FilmFormatID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("FilmFormatID") REFERENCES "FilmFormat"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_ProductionDate" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_ReleaseDate" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"ReleaseDate"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Runtime" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"Runtime"	TEXT,
	"EditionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Score" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"Score"	TEXT,
	"Date"	TEXT,
	"CompanyID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_SoundMix" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"SoundMixID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SoundMixID") REFERENCES "SoundMix"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Text" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_User" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"UserID"	TEXT,
	"EditionID"	TEXT,
	"UserStatusID"	TEXT,
	"PriorityID"	TEXT,
	"EnglishExplanation"	TEXT,
	"GermanExplanation"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PriorityID") REFERENCES "Priority"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserID") REFERENCES "User"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Movie_Weblink" (
	"ID"	TEXT NOT NULL,
	"MovieID"	TEXT,
	"WeblinkID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MovieID") REFERENCES "Movie"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("WeblinkID") REFERENCES "Weblink"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "MultiplayerGameMode" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "MultiplayerOption" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "OperatingSystem" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person" (
	"ID"	TEXT NOT NULL,
	"FirstName"	TEXT,
	"LastName"	TEXT,
	"NameAddOn"	TEXT,
	"BirthName"	TEXT,
	"DateOfBirth"	TEXT,
	"LocationOfBirthID"	TEXT,
	"DateOfDeath"	TEXT,
	"LocationOfDeathID"	TEXT,
	"EnglishCauseOfDeath"	TEXT,
	"GermanCauseOfDeath"	TEXT,
    "GenderID"    TEXT,
    "Height"    TEXT,
	"TypeID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
    FOREIGN KEY("GenderID") REFERENCES "Gender"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("LocationOfBirthID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("LocationOfDeathID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Employer" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"EmployerID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EmployerID") REFERENCES "Employer"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Family" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"FamilyID"	TEXT,
	"OriginalName"	TEXT,
	"RelationshipID"	TEXT,
    "EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("FamilyID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("RelationshipID") REFERENCES "Relationship"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Position" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"PositionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PositionID") REFERENCES "Position"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Profession" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"ProfessionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ProfessionID") REFERENCES "Profession"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Species" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"SpeciesID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SpeciesID") REFERENCES "Species"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Text" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Person_Weblink" (
	"ID"	TEXT NOT NULL,
	"PersonID"	TEXT,
	"WeblinkID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("WeblinkID") REFERENCES "Weblink"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Perspective" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Platform" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Position" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Priority" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Profession" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication" (
	"ID"	TEXT NOT NULL,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"ISBN13"	TEXT,
	"ISBN10"	TEXT,
	"BookID"	TEXT,
	"EditionID"	TEXT,
	"Format"	TEXT,
	"NoOfPages"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BookID") REFERENCES "Book"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication_Certification" (
	"ID"	TEXT NOT NULL,
	"PublicationID"	TEXT,
	"CertificationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CertificationID") REFERENCES "Certification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication_CompanyCredits" (
	"ID"	TEXT NOT NULL,
	"PublicationID"	TEXT,
	"CompanyID"	TEXT,
	"DepartmentID"	TEXT,
	"CountryID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication_Language" (
	"ID"	TEXT NOT NULL,
	"PublicationID"	TEXT,
	"LanguageID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication_ReleaseDate" (
	"ID"	TEXT NOT NULL,
	"PublicationID"	TEXT,
	"ReleaseDate"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Publication_Text" (
	"ID"	TEXT NOT NULL,
	"PublicationID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PublicationID") REFERENCES "Publication"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "RAM" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Relationship" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "SaveGameMethod" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series" (
	"ID"	TEXT NOT NULL,
	"OriginalTitle"	TEXT,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"TypeID"	TEXT,
	"NoOfSeasons"	TEXT,
	"NoOfEpisodes"	TEXT,
	"Budget"	TEXT,
	"WorldwideGross"	TEXT,
	"WorldwideGrossDate"	TEXT,
	"CastStatusID"	TEXT,
	"CrewStatusID"	TEXT,
	"ConnectionID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CastStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ConnectionID") REFERENCES "Connection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CrewStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_AspectRatio" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"AspectRatioID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AspectRatioID") REFERENCES "AspectRatio"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Award" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"AwardID"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	"Winner"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AwardID") REFERENCES "Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Award_Person" (
	"ID"	TEXT NOT NULL,
	"Series_AwardID"	TEXT,
	"PersonID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("Series_AwardID") REFERENCES "Series_Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Camera" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"CameraID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CameraID") REFERENCES "Camera"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Cast" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"ActorID"	TEXT,
	"EnglishDubberID"	TEXT,
	"GermanDubberID"	TEXT,
	"CharacterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ActorID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CharacterID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EnglishDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("GermanDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Certification" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"CertificationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CertificationID") REFERENCES "Certification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_CinematographicProcess" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"CinematographicProcessID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CinematographicProcessID") REFERENCES "CinematographicProcess"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Color" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"ColorID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ColorID") REFERENCES "Color"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_CompanyCredits" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"CompanyID"	TEXT,
	"DepartmentID"	TEXT,
	"CountryID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Country" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"CountryID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Crew" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"PersonID"	TEXT,
	"DepartmentID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_FilmLength" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"Length"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_FilmingDate" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_FilmingLocation" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"LocationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LocationID") REFERENCES "Location"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Genre" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"GenreID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("GenreID") REFERENCES "Genre"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Image" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"ImageID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "ImageType" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Laboratory" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"LaboratoryID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LaboratoryID") REFERENCES "Laboratory"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Language" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"LanguageID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_NegativeFormat" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"FilmFormatID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("FilmFormatID") REFERENCES "FilmFormat"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_PrintedFilmFormat" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"FilmFormatID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("FilmFormatID") REFERENCES "FilmFormat"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_ProductionDate" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"StartDate"	TEXT,
	"EndDate"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_ReleaseDateFirstEpisode" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"ReleaseDate"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_ReleaseDateLastEpisode" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"ReleaseDate"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Runtime" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"Runtime"	TEXT,
	"EditionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Score" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"Score"	TEXT,
	"Date"	TEXT,
	"CompanyID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_SoundMix" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"SoundMixID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SoundMixID") REFERENCES "SoundMix"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Text" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_User" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"UserID"	TEXT,
	"EditionID"	TEXT,
	"UserStatusID"	TEXT,
	"PriorityID"	TEXT,
	"EnglishExplanation"	TEXT,
	"GermanExplanation"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PriorityID") REFERENCES "Priority"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserID") REFERENCES "User"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Series_Weblink" (
	"ID"	TEXT NOT NULL,
	"SeriesID"	TEXT,
	"WeblinkID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SeriesID") REFERENCES "Series"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("WeblinkID") REFERENCES "Weblink"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Setting" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "SoundDevice" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "SoundMix" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "SoundMode" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Species" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Status" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "System" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"PlatformID"	TEXT,
	"BusinessModelID"	TEXT,
	"MinimumCPUClassID"	TEXT,
	"MinimumOSClassID"	TEXT,
	"MinimumRAMID"	TEXT,
	"MinimumDirectXID"	TEXT,
	"MinimumCDRomDriveSpeedID"	TEXT,
	"MinimumVideoRAMID"	TEXT,
	"NoOfPlayersOffline"	TEXT,
	"NoOfPlayersOfflineMultitap"	TEXT,
	"NoOfPlayersOnline"	TEXT,
	"EnglishAnnotation"	TEXT,
	"GermanAnnotation"	TEXT,
	"MiscAttributes"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("BusinessModelID") REFERENCES "BusinessModel"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumCDRomDriveSpeedID") REFERENCES "CDROMDriveSpeed"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumCPUClassID") REFERENCES "CPU"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumDirectXID") REFERENCES "DirectX"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumOSClassID") REFERENCES "OperatingSystem"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumRAMID") REFERENCES "RAM"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("MinimumVideoRAMID") REFERENCES "RAM"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_CopyProtection" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"CopyProtectionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CopyProtectionID") REFERENCES "CopyProtection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_MacOSSprocket" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"MacOSSprocketID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MacOSSprocketID") REFERENCES "MacOSSprocket"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_MediaType" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"MediaTypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MediaTypeID") REFERENCES "MediaType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_MultiplayerGameMode" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"MultiplayerGameModeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MultiplayerGameModeID") REFERENCES "MultiplayerGameMode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_MultiplayerOption" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"MultiplayerOptionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("MultiplayerOptionID") REFERENCES "MultiplayerOption"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_RequiredAdditionalHardware" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"HardwareID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("HardwareID") REFERENCES "Hardware"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_RequiredInputDevice" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"InputDeviceID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("InputDeviceID") REFERENCES "InputDevice"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SaveGameMethod" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"SaveGameMethodID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SaveGameMethodID") REFERENCES "SaveGameMethod"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedAdditionalHardware" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"HardwareID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("HardwareID") REFERENCES "Hardware"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedDriver" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"DriverID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DriverID") REFERENCES "Driver"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedInputDevice" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"InputDeviceID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("InputDeviceID") REFERENCES "InputDevice"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedInputDeviceFeature" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"InputDeviceFeatureID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("InputDeviceFeatureID") REFERENCES "InputDeviceFeature"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedSoundDevice" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"SoundDeviceID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SoundDeviceID") REFERENCES "SoundDevice"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedSoundMode" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"SoundModeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SoundModeID") REFERENCES "SoundMode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedVideoMode" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"VideoModeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoModeID") REFERENCES "VideoMode"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TechnicalSpecification_SupportedVideoResolution" (
	"ID"	TEXT NOT NULL,
	"TechnicalSpecificationID"	TEXT,
	"VideoResolutionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TechnicalSpecificationID") REFERENCES "TechnicalSpecification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoResolutionID") REFERENCES "VideoResolution"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Text" (
	"ID"	TEXT NOT NULL,
	"Content"	TEXT,
	"LanguageID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Text_Author" (
	"ID"	TEXT NOT NULL,
	"TextID"	TEXT,
	"PersonID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Text_Source" (
	"ID"	TEXT NOT NULL,
	"TextID"	TEXT,
	"CompanyID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "TextType" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Type" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "User" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"EMail"	TEXT,
	"PersonID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Version" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"ReleaseDate"	TEXT,
	"TypeID"	TEXT,
	"PlatformID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame" (
	"ID"	TEXT NOT NULL,
	"OriginalTitle"	TEXT,
	"EnglishTitle"	TEXT,
	"GermanTitle"	TEXT,
	"TypeID"	TEXT,
	"Budget"	TEXT,
	"WorldwideGross"	TEXT,
	"WorldwideGrossDate"	TEXT,
	"CastStatusID"	TEXT,
	"CrewStatusID"	TEXT,
	"ConnectionID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CastStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CrewStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("ConnectionID") REFERENCES "Connection"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "Type"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Award" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"AwardID"	TEXT,
	"Category"	TEXT,
	"Date"	TEXT,
	"Winner"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("AwardID") REFERENCES "Award"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Cast" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"ActorID"	TEXT,
	"EnglishDubberID"	TEXT,
	"GermanDubberID"	TEXT,
	"CharacterID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ActorID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CharacterID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("EnglishDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("GermanDubberID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Certification" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"CertificationID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CertificationID") REFERENCES "Certification"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_CompanyCredits" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"CompanyID"	TEXT,
	"DepartmentID"	TEXT,
	"PlatformID"	TEXT,
	"CountryID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("CountryID") REFERENCES "Country"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Completion" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"CompletionStatusID"	TEXT,
	"PlatformID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompletionStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Crew" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"PersonID"	TEXT,
	"DepartmentID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DepartmentID") REFERENCES "Department"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PersonID") REFERENCES "Person"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Difficulty" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"DifficultyID"	TEXT,
	"PlatformID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("DifficultyID") REFERENCES "Difficulty"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Genre" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"GenreID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("GenreID") REFERENCES "Genre"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Image" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"ImageID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("ImageID") REFERENCES "Image"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "ImageType" ("ID") ON UPDATE CASCADE ON DELETE RESTRICT
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Language" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"LanguageID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Perspective" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"PerspectiveID"	TEXT,
	"PlatformID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PerspectiveID") REFERENCES "Perspective"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_ReleaseDate" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"ReleaseDate"	TEXT,
	"PlatformID"	TEXT,
	"EnglishDescription"	TEXT,
	"GermanDescription"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Score" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"Score"	TEXT,
	"Date"	TEXT,
	"CompanyID"	TEXT,
	"PlatformID"	TEXT,
	"EnglishRole"	TEXT,
	"GermanRole"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("CompanyID") REFERENCES "Company"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PlatformID") REFERENCES "Platform"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Setting" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"SettingID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("SettingID") REFERENCES "Setting"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Text" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"TextID"	TEXT,
	"TypeID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TextID") REFERENCES "Text"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("TypeID") REFERENCES "TextType"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_User" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"UserID"	TEXT,
	"EditionID"	TEXT,
	"UserStatusID"	TEXT,
	"PriorityID"	TEXT,
	"EnglishExplanation"	TEXT,
	"GermanExplanation"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("EditionID") REFERENCES "Edition"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("PriorityID") REFERENCES "Priority"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserID") REFERENCES "User"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("UserStatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Version" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"VersionID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VersionID") REFERENCES "Version"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoGame_Weblink" (
	"ID"	TEXT NOT NULL,
	"VideoGameID"	TEXT,
	"WeblinkID"	TEXT,
	"Order"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("VideoGameID") REFERENCES "VideoGame"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("WeblinkID") REFERENCES "Weblink"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoMode" (
	"ID"	TEXT NOT NULL,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "VideoResolution" (
	"ID"	TEXT NOT NULL,
	"OriginalName"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS "Weblink" (
	"ID"	TEXT NOT NULL,
	"URL"	TEXT,
	"EnglishName"	TEXT,
	"GermanName"	TEXT,
	"LanguageID"	TEXT,
	"Details"	TEXT,
	"Notes"	TEXT,
	"StatusID"	TEXT,
	"LastUpdated"	TEXT,
	PRIMARY KEY("ID"),
	FOREIGN KEY("LanguageID") REFERENCES "Language"("ID") ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY("StatusID") REFERENCES "Status"("ID") ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE VIEW "CastList" AS
SELECT Movie_Cast.MovieID, Movie_Cast.ActorID, Person.FirstName, Person.LastName, Person.NameAddOn, Movie_Cast.EnglishRole, Movie_Cast.GermanRole, Movie_Cast.Details, Movie_Cast.Notes
FROM Movie_Cast, Person
WHERE Movie_Cast.ActorID = Person.ID
UNION
SELECT Series_Cast.SeriesID, Series_Cast.ActorID, Person.FirstName, Person.LastName, Person.NameAddOn, Series_Cast.EnglishRole, Series_Cast.GermanRole, Series_Cast.Details, Series_Cast.Notes
FROM Series_Cast, Person
WHERE Series_Cast.ActorID = Person.ID;

/*
CREATE VIEW "SeriesCastList" AS
SELECT Episode_Cast.EpisodeID, Episode_Cast.ActorID, Person.FirstName, Person.LastName, Person.NameAddOn, Episode_Cast.EnglishRole, Episode_Cast.GermanRole, Episode_Cast.Details, Episode_Cast.Notes
FROM Episode_Cast, Person
WHERE Episode_Cast.ActorID = Person.ID;
*/

COMMIT;
