namespace WikiExporter.Persistence.Queries;

/// <summary>Explicit allow-lists keep graph traversal bounded to data belonging to the requested export type.</summary>
internal static class RootGraphPlans
{
    internal static readonly IReadOnlySet<string> Movie = new HashSet<string>(StringComparer.Ordinal) { "Movie", "Movie_AspectRatio", "Movie_Award", "Movie_Award_Person", "Movie_Camera", "Movie_Cast", "Movie_Certification", "Movie_CinematographicProcess", "Movie_Color", "Movie_CompanyCredits", "Movie_Country", "Movie_Crew", "Movie_FilmLength", "Movie_FilmingDate", "Movie_FilmingLocation", "Movie_Genre", "Movie_Image", "Movie_Laboratory", "Movie_Language", "Movie_NegativeFormat", "Movie_PrintedFilmFormat", "Movie_ProductionDate", "Movie_ReleaseDate", "Movie_Runtime", "Movie_Score", "Movie_SoundMix", "Movie_Text", "Movie_Weblink", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> Series = new HashSet<string>(StringComparer.Ordinal) { "Series", "Series_AspectRatio", "Series_Award", "Series_Award_Person", "Series_Camera", "Series_Cast", "Series_Certification", "Series_CinematographicProcess", "Series_Color", "Series_CompanyCredits", "Series_Country", "Series_Crew", "Series_FilmLength", "Series_FilmingDate", "Series_FilmingLocation", "Series_Genre", "Series_Image", "Series_Laboratory", "Series_Language", "Series_NegativeFormat", "Series_PrintedFilmFormat", "Series_ProductionDate", "Series_ReleaseDateFirstEpisode", "Series_ReleaseDateLastEpisode", "Series_Runtime", "Series_Score", "Series_SoundMix", "Series_Text", "Series_Weblink", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> Episode = new HashSet<string>(StringComparer.Ordinal) { "Episode", "Episode_Award", "Episode_Award_Person", "Episode_Cast", "Episode_Certification", "Episode_CompanyCredits", "Episode_Crew", "Episode_FilmLength", "Episode_FilmingDate", "Episode_FilmingLocation", "Episode_Image", "Episode_ProductionDate", "Episode_ReleaseDate", "Episode_Runtime", "Episode_Text", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> Book = new HashSet<string>(StringComparer.Ordinal) { "Book", "Book_Award", "Book_Cast", "Book_Crew", "Book_Genre", "Book_Image", "Book_Language", "Book_Score", "Book_Text", "Book_Weblink", "Publication", "Publication_Certification", "Publication_CompanyCredits", "Publication_Language", "Publication_ReleaseDate", "Publication_Text", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> VideoGame = new HashSet<string>(StringComparer.Ordinal) { "VideoGame", "VideoGame_Award", "VideoGame_Cast", "VideoGame_Certification", "VideoGame_CompanyCredits", "VideoGame_Completion", "VideoGame_Crew", "VideoGame_Difficulty", "VideoGame_Genre", "VideoGame_Image", "VideoGame_Language", "VideoGame_Perspective", "VideoGame_ReleaseDate", "VideoGame_Score", "VideoGame_Setting", "VideoGame_Text", "VideoGame_Version", "VideoGame_Weblink", "TechnicalSpecification", "TechnicalSpecification_CopyProtection", "TechnicalSpecification_MacOSSprocket", "TechnicalSpecification_MediaType", "TechnicalSpecification_MultiplayerGameMode", "TechnicalSpecification_MultiplayerOption", "TechnicalSpecification_RequiredAdditionalHardware", "TechnicalSpecification_RequiredInputDevice", "TechnicalSpecification_SaveGameMethod", "TechnicalSpecification_SupportedAdditionalHardware", "TechnicalSpecification_SupportedDriver", "TechnicalSpecification_SupportedInputDevice", "TechnicalSpecification_SupportedInputDeviceFeature", "TechnicalSpecification_SupportedSoundDevice", "TechnicalSpecification_SupportedSoundMode", "TechnicalSpecification_SupportedVideoMode", "TechnicalSpecification_SupportedVideoResolution", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> Person = new HashSet<string>(StringComparer.Ordinal) { "Person", "Person_Employer", "Person_Family", "Person_Position", "Person_Profession", "Person_Species", "Person_Text", "Person_Weblink", "Text_Author", "Text_Source", "Image_Source" };
    internal static readonly IReadOnlySet<string> Connection = new HashSet<string>(StringComparer.Ordinal) { "Connection" };
}
